#!/bin/bash

echo "🔐 GitHub Token Setup for Private Repository Access"
echo "=================================================="
echo ""
echo "Since your repository is private, you'll need a GitHub Personal Access Token"
echo "to download the PDF from the release."
echo ""
echo "Steps to create a token:"
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Click 'Generate new token (classic)'"
echo "3. Give it a name like 'Blake Bibliography PDF Access'"
echo "4. Select the 'repo' scope (full repository access)"
echo "5. Set an expiration date"
echo "6. Click 'Generate token'"
echo "7. Copy the token (you won't see it again!)"
echo ""
echo "Then run:"
echo "export GITHUB_TOKEN=your_token_here"
echo "./test-release-url.sh"
echo ""
echo "Or for Docker builds:"
echo "docker build --build-arg GITHUB_TOKEN=your_token_here -t blake-backend ."
echo ""
echo "Alternative: Make the release public"
echo "===================================="
echo "1. Go to your GitHub release page"
echo "2. Edit the release"
echo "3. Check the option to make it publicly accessible"
echo "4. This allows downloads without authentication"
