apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: blake-bibliography-backend
  namespace: blake-bibliography
  labels:
    app: blake-bibliography-backend
spec:
  source:
    type: Git
    git:
      uri: https://github.com/blakearchive/william-blake-bibliography-viewer.git
    contextDir: backend
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: blake-bibliography-backend:latest
  triggers:
  - type: ConfigChange
  - type: GitHub
    github:
      secret: github-webhook-secret
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: blake-bibliography-frontend
  namespace: blake-bibliography
  labels:
    app: blake-bibliography-frontend
spec:
  source:
    type: Git
    git:
      uri: https://github.com/blakearchive/william-blake-bibliography-viewer.git
    contextDir: frontend
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: blake-bibliography-frontend:latest
  triggers:
  - type: ConfigChange
  - type: GitHub
    github:
      secret: github-webhook-secret
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: blake-bibliography-backend
  namespace: blake-bibliography
  labels:
    app: blake-bibliography-backend
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: blake-bibliography-frontend
  namespace: blake-bibliography
  labels:
    app: blake-bibliography-frontend
